"""A1, A2 ve B1 seviyeleri için başlangıç kelimelerini toplu ekler.

Kullanım (proje ana klasöründe):
    python3 seed_vocabulary.py

Birden fazla kez çalıştırmak güvenlidir: zaten kayıtlı kelimeler atlanır.
"""

from database import init_db
from models import Level
from services import vocabulary_service

WORDS: dict[Level, list[tuple[str, str]]] = {
    Level.A1: [
        ("der Tag", "gün"),
        ("die Woche", "hafta"),
        ("der Monat", "ay"),
        ("das Jahr", "yıl"),
        ("die Zeit", "zaman"),
        ("der Morgen", "sabah"),
        ("der Abend", "akşam"),
        ("die Nacht", "gece"),
        ("heute", "bugün"),
        ("morgen", "yarın"),
        ("gestern", "dün"),
        ("das Haus", "ev"),
        ("die Wohnung", "daire"),
        ("das Zimmer", "oda"),
        ("die Küche", "mutfak"),
        ("die Tür", "kapı"),
        ("das Fenster", "pencere"),
        ("der Tisch", "masa"),
        ("der Stuhl", "sandalye"),
        ("das Bett", "yatak"),
        ("die Familie", "aile"),
        ("die Mutter", "anne"),
        ("der Vater", "baba"),
        ("der Bruder", "erkek kardeş"),
        ("die Schwester", "kız kardeş"),
        ("das Kind", "çocuk"),
        ("der Freund", "arkadaş (erkek)"),
        ("die Freundin", "arkadaş (kadın)"),
        ("der Mann", "adam, koca"),
        ("die Frau", "kadın, eş"),
        ("das Essen", "yemek"),
        ("das Brot", "ekmek"),
        ("das Obst", "meyve"),
        ("das Gemüse", "sebze"),
        ("die Milch", "süt"),
        ("das Wasser", "su"),
        ("der Kaffee", "kahve"),
        ("der Tee", "çay"),
        ("der Apfel", "elma"),
        ("das Fleisch", "et"),
        ("der Käse", "peynir"),
        ("die Schule", "okul"),
        ("der Lehrer", "öğretmen"),
        ("das Buch", "kitap"),
        ("der Stift", "kalem"),
        ("die Hausaufgabe", "ödev"),
        ("die Arbeit", "iş"),
        ("das Geld", "para"),
        ("die Stadt", "şehir"),
        ("die Straße", "sokak, cadde"),
        ("der Bahnhof", "tren istasyonu"),
        ("das Auto", "araba"),
        ("der Bus", "otobüs"),
        ("das Wetter", "hava durumu"),
        ("heißen", "adı ... olmak"),
        ("wohnen", "oturmak (ikamet)"),
        ("kommen", "gelmek"),
        ("gehen", "gitmek"),
        ("machen", "yapmak"),
        ("essen", "yemek yemek"),
        ("trinken", "içmek"),
        ("lernen", "öğrenmek"),
        ("sprechen", "konuşmak"),
        ("haben", "sahip olmak"),
        ("sein", "olmak"),
        ("kaufen", "satın almak"),
        ("groß", "büyük"),
        ("klein", "küçük"),
        ("gut", "iyi"),
        ("schlecht", "kötü"),
        ("neu", "yeni"),
        ("alt", "eski, yaşlı"),
        ("schön", "güzel"),
    ],
    Level.A2: [
        ("arbeiten", "çalışmak"),
        ("besuchen", "ziyaret etmek"),
        ("bestellen", "sipariş etmek"),
        ("bezahlen", "ödemek"),
        ("brauchen", "ihtiyaç duymak"),
        ("finden", "bulmak"),
        ("fahren", "gitmek (araçla)"),
        ("helfen", "yardım etmek"),
        ("kennen", "tanımak"),
        ("kochen", "pişirmek"),
        ("lesen", "okumak"),
        ("schreiben", "yazmak"),
        ("schlafen", "uyumak"),
        ("suchen", "aramak"),
        ("verstehen", "anlamak"),
        ("vergessen", "unutmak"),
        ("warten", "beklemek"),
        ("wissen", "bilmek"),
        ("zeigen", "göstermek"),
        ("mieten", "kiralamak"),
        ("der Termin", "randevu"),
        ("der Urlaub", "tatil"),
        ("die Reise", "yolculuk"),
        ("der Flughafen", "havalimanı"),
        ("die Fahrkarte", "bilet"),
        ("die Haltestelle", "durak"),
        ("der Arzt", "doktor"),
        ("die Krankheit", "hastalık"),
        ("die Gesundheit", "sağlık"),
        ("der Kopf", "baş"),
        ("die Hand", "el"),
        ("das Gesicht", "yüz"),
        ("die Rechnung", "fatura, hesap"),
        ("das Angebot", "teklif, kampanya"),
        ("die Meinung", "görüş"),
        ("die Frage", "soru"),
        ("die Antwort", "cevap"),
        ("das Problem", "sorun"),
        ("die Idee", "fikir"),
        ("der Unterschied", "fark"),
        ("das Beispiel", "örnek"),
        ("das Geschenk", "hediye"),
        ("die Party", "parti"),
        ("der Nachbar", "komşu"),
        ("die Nachricht", "haber, mesaj"),
        ("der Anruf", "telefon görüşmesi"),
        ("die Miete", "kira"),
        ("der Vertrag", "sözleşme"),
        ("die Ausbildung", "meslek eğitimi"),
        ("der Beruf", "meslek"),
        ("die Firma", "şirket"),
        ("der Kollege", "iş arkadaşı"),
        ("das Gehalt", "maaş"),
        ("wichtig", "önemli"),
        ("schwierig", "zor"),
        ("einfach", "kolay, basit"),
        ("freundlich", "arkadaş canlısı"),
        ("müde", "yorgun"),
        ("krank", "hasta"),
        ("frei", "boş, özgür"),
        ("möglich", "mümkün"),
        ("leider", "maalesef"),
        ("sofort", "hemen"),
        ("ungefähr", "yaklaşık"),
        ("oft", "sık sık"),
        ("manchmal", "bazen"),
        ("niemals", "asla"),
    ],
    Level.B1: [
        ("die Erfahrung", "deneyim"),
        ("sich entscheiden", "karar vermek"),
        ("sich beschweren", "şikayet etmek"),
        ("sich bewerben", "başvurmak"),
        ("sich erinnern", "hatırlamak"),
        ("sich interessieren für", "ilgilenmek"),
        ("sich freuen auf", "dört gözle beklemek"),
        ("sich kümmern um", "ilgilenmek, bakmak"),
        ("sich vorbereiten", "hazırlanmak"),
        ("sich verabreden", "buluşmak için sözleşmek"),
        ("vorschlagen", "önermek"),
        ("erklären", "açıklamak"),
        ("erzählen", "anlatmak"),
        ("vermeiden", "kaçınmak"),
        ("verbessern", "geliştirmek, iyileştirmek"),
        ("vergleichen", "karşılaştırmak"),
        ("verändern", "değiştirmek"),
        ("verpassen", "kaçırmak"),
        ("unterstützen", "desteklemek"),
        ("überzeugen", "ikna etmek"),
        ("die Bewerbung", "başvuru"),
        ("der Lebenslauf", "özgeçmiş"),
        ("das Vorstellungsgespräch", "iş görüşmesi"),
        ("die Kündigung", "işten çıkarma, fesih"),
        ("die Verantwortung", "sorumluluk"),
        ("die Entscheidung", "karar"),
        ("die Möglichkeit", "olanak, imkan"),
        ("die Gelegenheit", "fırsat"),
        ("die Voraussetzung", "ön koşul"),
        ("die Umwelt", "çevre"),
        ("die Gesellschaft", "toplum"),
        ("die Wirtschaft", "ekonomi"),
        ("die Regierung", "hükümet"),
        ("das Ergebnis", "sonuç"),
        ("der Vorteil", "avantaj"),
        ("der Nachteil", "dezavantaj"),
        ("der Einfluss", "etki"),
        ("der Grund", "neden"),
        ("die Absicht", "niyet"),
        ("die Ahnung", "fikir, haber"),
        ("die Beziehung", "ilişki"),
        ("das Erlebnis", "yaşanmış olay"),
        ("die Entwicklung", "gelişme, gelişim"),
        ("die Erklärung", "açıklama"),
        ("der Zusammenhang", "bağlantı"),
        ("selbstständig", "bağımsız"),
        ("zuverlässig", "güvenilir"),
        ("ehrlich", "dürüst"),
        ("vorsichtig", "dikkatli"),
        ("wahrscheinlich", "muhtemelen"),
        ("tatsächlich", "gerçekten"),
        ("trotzdem", "yine de"),
        ("deshalb", "bu yüzden"),
        ("außerdem", "ayrıca"),
        ("obwohl", "-e rağmen"),
        ("während", "-erken, süresince"),
        ("allerdings", "ancak, fakat"),
        ("nämlich", "çünkü (açıklayıcı)"),
    ],
}


def main() -> None:
    init_db()

    added = 0
    skipped = 0
    for level, words in WORDS.items():
        level_added = 0
        for german, turkish in words:
            result = vocabulary_service.add_word(german, turkish, level)
            if result is None:
                skipped += 1
            else:
                added += 1
                level_added += 1
        print(f"{level.value}: {level_added} yeni kelime eklendi")

    print(f"\nToplam eklenen: {added}, zaten kayıtlı olduğu için atlanan: {skipped}")


if __name__ == "__main__":
    main()